language: go
go:
  - 1.11.x
  - tip
env:
  - GO111MODULE=on
  - CODECOV_TOKEN=3c708926-3884-4f39-a33f-76931b762ea4
install:
  - go get -v golang.org/x/lint/golint
script:
  - golint -set_exit_status ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - go: tip